# Generated by Django 4.2.1 on 2023-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='profession',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
